name: Deploy Vite React App to Pages

on:
  push:
    branches: 
     -main
     -master

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show root files
        run: ls -R

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show chatbot-project files before install
        run: ls -R ./chatbot-project

      - name: Install dependencies
        run: npm install
        working-directory: ./chatbot-project

      - name: Build project
        run: npm run build
        working-directory: ./chatbot-project

      - name: Show chatbot-project files after build
        run: ls -R ./chatbot-project

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./chatbot-project/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
